console.log("Hello from external Javascript!");
alert("Welcome to Gen's Website!");
let userInput = prompt("What is your favorite color of all time?");
alert("My favorite color is " + userInput + " too!");
let littleMermaidPrice = 3;
let brotherBearPrice = 5;
let herculesPrice = 1;
let littleMermaidDays = 3;
let brotherBearDays = 5;
let herculesDays = 1;
let totalPaid = ((littleMermaidPrice * littleMermaidDays) + (brotherBearDays * brotherBearPrice) + (herculesDays * herculesPrice));
prompt("Do you know the total price of your 3 movie rentals?");
let userInput1 = alert("Your total price is " + totalPaid + " dollars!");
let googleRPH = 400;
let amazonRPH = 380;
let facebookRPH = 350;
let googleHoursWorked = 6;
let amazonHoursWorked = 4;
let facebookHoursWorked = 10;
let totalPay = ((googleRPH * googleHoursWorked) + (amazonRPH * amazonHoursWorked) + (facebookRPH * facebookHoursWorked));
prompt("How much do you think your 3 primary companies owe you?");
let userInput2 = alert("Your total pay is " + totalPay + " dollars! WOW!");
let twoItemsOrMore = true;
let offerNotExpired = true;
let premiumMembers = true;
prompt("Are you a premium member? Type Y for Yes/N for No.");
alert("If you are not a Premium member, the offer is valid if you buy 2 or more items AND if the offer has not expired!");
let classNotFull = true;
let nonconflictingSchedule = false;
prompt("Is your class full?");
prompt("Does the class schedule conflict with your own schedule?");
nonconflictingSchedule === (alert("We're sorry. You are unable to enroll."));